# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stegosoft.ui'
#
# Created: Fri Aug  5 05:42:53 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_stegosoft_gui(object):
    def setupUi(self, stegosoft_gui):
        stegosoft_gui.setObjectName("stegosoft_gui")
        stegosoft_gui.resize(800, 633)
        self.tabWidget = QtGui.QTabWidget(stegosoft_gui)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 633))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtCore.Qt.PointingHandCursor)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_hide = QtGui.QWidget()
        self.tab_hide.setObjectName("tab_hide")
        self.label = QtGui.QLabel(self.tab_hide)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label.setCursor(QtCore.Qt.ArrowCursor)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/hide_theme.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtGui.QLabel(self.tab_hide)
        self.label_6.setGeometry(QtCore.QRect(31, 515, 181, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtCore.Qt.ArrowCursor)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_6.setFrameShadow(QtGui.QFrame.Plain)
        self.label_6.setObjectName("label_6")
        self.pushButton_remove_message_file = QtGui.QPushButton(self.tab_hide)
        self.pushButton_remove_message_file.setGeometry(QtCore.QRect(131, 407, 91, 21))
        self.pushButton_remove_message_file.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_remove_message_file.setObjectName("pushButton_remove_message_file")
        self.tableWidget_for_hide_message_files = QtGui.QTableWidget(self.tab_hide)
        self.tableWidget_for_hide_message_files.setGeometry(QtCore.QRect(472, 244, 313, 252))
        self.tableWidget_for_hide_message_files.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.tableWidget_for_hide_message_files.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_for_hide_message_files.setAlternatingRowColors(True)
        self.tableWidget_for_hide_message_files.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_for_hide_message_files.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_for_hide_message_files.setObjectName("tableWidget_for_hide_message_files")
        self.tableWidget_for_hide_message_files.setColumnCount(4)
        self.tableWidget_for_hide_message_files.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_for_hide_message_files.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_for_hide_message_files.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_for_hide_message_files.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_for_hide_message_files.setHorizontalHeaderItem(3, item)
        self.lineEdit_hide_password = QtGui.QLineEdit(self.tab_hide)
        self.lineEdit_hide_password.setGeometry(QtCore.QRect(217, 492, 133, 17))
        self.lineEdit_hide_password.setObjectName("lineEdit_hide_password")
        self.label_4 = QtGui.QLabel(self.tab_hide)
        self.label_4.setGeometry(QtCore.QRect(10, 459, 149, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtCore.Qt.ArrowCursor)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setObjectName("label_4")
        self.pushButton_browse_master_file = QtGui.QPushButton(self.tab_hide)
        self.pushButton_browse_master_file.setEnabled(True)
        self.pushButton_browse_master_file.setGeometry(QtCore.QRect(186, 289, 91, 21))
        self.pushButton_browse_master_file.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_browse_master_file.setMouseTracking(False)
        self.pushButton_browse_master_file.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_browse_master_file.setAcceptDrops(False)
        self.pushButton_browse_master_file.setAutoFillBackground(False)
        self.pushButton_browse_master_file.setCheckable(False)
        self.pushButton_browse_master_file.setObjectName("pushButton_browse_master_file")
        self.label_master_file_path = QtGui.QLabel(self.tab_hide)
        self.label_master_file_path.setGeometry(QtCore.QRect(10, 321, 200, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.label_master_file_path.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_master_file_path.setFont(font)
        self.label_master_file_path.setCursor(QtCore.Qt.ArrowCursor)
        self.label_master_file_path.setAutoFillBackground(False)
        self.label_master_file_path.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_master_file_path.setFrameShadow(QtGui.QFrame.Plain)
        self.label_master_file_path.setScaledContents(True)
        self.label_master_file_path.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_master_file_path.setObjectName("label_master_file_path")
        self.pushButton_add_message_file = QtGui.QPushButton(self.tab_hide)
        self.pushButton_add_message_file.setGeometry(QtCore.QRect(12, 407, 91, 21))
        self.pushButton_add_message_file.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_add_message_file.setObjectName("pushButton_add_message_file")
        self.label_master_file_size = QtGui.QLabel(self.tab_hide)
        self.label_master_file_size.setGeometry(QtCore.QRect(216, 321, 59, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.label_master_file_size.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_master_file_size.setFont(font)
        self.label_master_file_size.setCursor(QtCore.Qt.ArrowCursor)
        self.label_master_file_size.setAutoFillBackground(False)
        self.label_master_file_size.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_master_file_size.setFrameShadow(QtGui.QFrame.Plain)
        self.label_master_file_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_master_file_size.setObjectName("label_master_file_size")
        self.pushButton_hide_submit = QtGui.QPushButton(self.tab_hide)
        self.pushButton_hide_submit.setGeometry(QtCore.QRect(344, 558, 105, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_hide_submit.setFont(font)
        self.pushButton_hide_submit.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_hide_submit.setObjectName("pushButton_hide_submit")
        self.label_3 = QtGui.QLabel(self.tab_hide)
        self.label_3.setGeometry(QtCore.QRect(11, 371, 220, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtCore.Qt.ArrowCursor)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Plain)
        self.label_3.setObjectName("label_3")
        self.lineEdit_hide_confirm_password = QtGui.QLineEdit(self.tab_hide)
        self.lineEdit_hide_confirm_password.setGeometry(QtCore.QRect(217, 519, 133, 17))
        self.lineEdit_hide_confirm_password.setObjectName("lineEdit_hide_confirm_password")
        self.checkBox_use_password = QtGui.QCheckBox(self.tab_hide)
        self.checkBox_use_password.setGeometry(QtCore.QRect(155, 463, 24, 19))
        self.checkBox_use_password.setCursor(QtCore.Qt.PointingHandCursor)
        self.checkBox_use_password.setText("")
        self.checkBox_use_password.setChecked(False)
        self.checkBox_use_password.setObjectName("checkBox_use_password")
        self.label_5 = QtGui.QLabel(self.tab_hide)
        self.label_5.setGeometry(QtCore.QRect(31, 489, 172, 27))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtCore.Qt.ArrowCursor)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtGui.QLabel(self.tab_hide)
        self.label_2.setGeometry(QtCore.QRect(10, 290, 181, 17))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 240, 203))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 255, 233))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Palladio L")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtCore.Qt.ArrowCursor)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtGui.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_hide, "")
        self.tab_unhide = QtGui.QWidget()
        self.tab_unhide.setObjectName("tab_unhide")
        self.label_9 = QtGui.QLabel(self.tab_unhide)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.label_9.setCursor(QtCore.Qt.ArrowCursor)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("images/unhide_theme.jpg"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.tab_unhide)
        self.label_10.setGeometry(QtCore.QRect(8, 185, 291, 37))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 233, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 233, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 118, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setCursor(QtCore.Qt.ArrowCursor)
        self.label_10.setObjectName("label_10")
        self.pushButton_browse_carrier_file = QtGui.QPushButton(self.tab_unhide)
        self.pushButton_browse_carrier_file.setGeometry(QtCore.QRect(101, 287, 97, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse_carrier_file.setFont(font)
        self.pushButton_browse_carrier_file.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_browse_carrier_file.setObjectName("pushButton_browse_carrier_file")
        self.label_carrier_file_size = QtGui.QLabel(self.tab_unhide)
        self.label_carrier_file_size.setGeometry(QtCore.QRect(116, 360, 64, 17))
        self.label_carrier_file_size.setCursor(QtCore.Qt.ArrowCursor)
        self.label_carrier_file_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_carrier_file_size.setObjectName("label_carrier_file_size")
        self.label_carrier_file_path = QtGui.QLabel(self.tab_unhide)
        self.label_carrier_file_path.setGeometry(QtCore.QRect(70, 395, 153, 24))
        self.label_carrier_file_path.setCursor(QtCore.Qt.ArrowCursor)
        self.label_carrier_file_path.setScaledContents(True)
        self.label_carrier_file_path.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_carrier_file_path.setObjectName("label_carrier_file_path")
        self.lineEdit_unhide_password = QtGui.QLineEdit(self.tab_unhide)
        self.lineEdit_unhide_password.setGeometry(QtCore.QRect(635, 268, 117, 21))
        self.lineEdit_unhide_password.setObjectName("lineEdit_unhide_password")
        self.pushButton_unhide_submit = QtGui.QPushButton(self.tab_unhide)
        self.pushButton_unhide_submit.setGeometry(QtCore.QRect(638, 425, 123, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_unhide_submit.setFont(font)
        self.pushButton_unhide_submit.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_unhide_submit.setObjectName("pushButton_unhide_submit")
        self.tableWidget_for_unhide_message_files = QtGui.QTableWidget(self.tab_unhide)
        self.tableWidget_for_unhide_message_files.setGeometry(QtCore.QRect(7, 476, 303, 118))
        self.tableWidget_for_unhide_message_files.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.tableWidget_for_unhide_message_files.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_for_unhide_message_files.setAlternatingRowColors(True)
        self.tableWidget_for_unhide_message_files.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_for_unhide_message_files.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_for_unhide_message_files.setShowGrid(False)
        self.tableWidget_for_unhide_message_files.setObjectName("tableWidget_for_unhide_message_files")
        self.tableWidget_for_unhide_message_files.setColumnCount(3)
        self.tableWidget_for_unhide_message_files.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_for_unhide_message_files.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_for_unhide_message_files.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_for_unhide_message_files.setHorizontalHeaderItem(2, item)
        self.pushButton_show_message_files = QtGui.QPushButton(self.tab_unhide)
        self.pushButton_show_message_files.setGeometry(QtCore.QRect(8, 450, 97, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_show_message_files.setFont(font)
        self.pushButton_show_message_files.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_show_message_files.setObjectName("pushButton_show_message_files")
        self.tabWidget.addTab(self.tab_unhide, "")
        self.tab_help = QtGui.QWidget()
        self.tab_help.setObjectName("tab_help")
        self.webView_help = QtWebKit.QWebView(self.tab_help)
        self.webView_help.setGeometry(QtCore.QRect(0, 0, 796, 598))
        self.webView_help.setUrl(QtCore.QUrl("file:///media/Dustbin/Google/Final Year Projcet/Project_folder/documentation/documentation.html"))
        self.webView_help.setObjectName("webView_help")
        self.tabWidget.addTab(self.tab_help, "")
        self.tab_about = QtGui.QWidget()
        self.tab_about.setObjectName("tab_about")
        self.textEdit = QtGui.QTextEdit(self.tab_about)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 797, 600))
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_about, "")

        self.retranslateUi(stegosoft_gui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(stegosoft_gui)
        stegosoft_gui.setTabOrder(self.pushButton_browse_master_file, self.pushButton_add_message_file)
        stegosoft_gui.setTabOrder(self.pushButton_add_message_file, self.pushButton_remove_message_file)
        stegosoft_gui.setTabOrder(self.pushButton_remove_message_file, self.checkBox_use_password)
        stegosoft_gui.setTabOrder(self.checkBox_use_password, self.lineEdit_hide_password)
        stegosoft_gui.setTabOrder(self.lineEdit_hide_password, self.lineEdit_hide_confirm_password)
        stegosoft_gui.setTabOrder(self.lineEdit_hide_confirm_password, self.pushButton_hide_submit)
        stegosoft_gui.setTabOrder(self.pushButton_hide_submit, self.tableWidget_for_hide_message_files)
        stegosoft_gui.setTabOrder(self.tableWidget_for_hide_message_files, self.tabWidget)
        stegosoft_gui.setTabOrder(self.tabWidget, self.pushButton_browse_carrier_file)
        stegosoft_gui.setTabOrder(self.pushButton_browse_carrier_file, self.lineEdit_unhide_password)
        stegosoft_gui.setTabOrder(self.lineEdit_unhide_password, self.pushButton_unhide_submit)
        stegosoft_gui.setTabOrder(self.pushButton_unhide_submit, self.tableWidget_for_unhide_message_files)

    def retranslateUi(self, stegosoft_gui):
        stegosoft_gui.setWindowTitle(QtGui.QApplication.translate("stegosoft_gui", "StegoSoft - Hide Anything", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("stegosoft_gui", "Confirm Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_message_file.setText(QtGui.QApplication.translate("stegosoft_gui", "Remove File", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_for_hide_message_files.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("stegosoft_gui", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_for_hide_message_files.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("stegosoft_gui", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_for_hide_message_files.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("stegosoft_gui", "Encrypt", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_for_hide_message_files.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("stegosoft_gui", "Full Path", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_hide_password.setText(QtGui.QApplication.translate("stegosoft_gui", "Type Here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("stegosoft_gui", "Use Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browse_master_file.setText(QtGui.QApplication.translate("stegosoft_gui", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_master_file_path.setText(QtGui.QApplication.translate("stegosoft_gui", "No File Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_message_file.setText(QtGui.QApplication.translate("stegosoft_gui", "Add File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_master_file_size.setText(QtGui.QApplication.translate("stegosoft_gui", "Size 0 KB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hide_submit.setText(QtGui.QApplication.translate("stegosoft_gui", "HIDE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("stegosoft_gui", "Select Message File (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_hide_confirm_password.setText(QtGui.QApplication.translate("stegosoft_gui", "Type Here", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("stegosoft_gui", "Enter Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("stegosoft_gui", "Select Master File:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hide), QtGui.QApplication.translate("stegosoft_gui", "HIDE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("stegosoft_gui", "Select Carrier File:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browse_carrier_file.setText(QtGui.QApplication.translate("stegosoft_gui", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_carrier_file_size.setText(QtGui.QApplication.translate("stegosoft_gui", "Size 0KB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_carrier_file_path.setText(QtGui.QApplication.translate("stegosoft_gui", "No File Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_unhide_password.setText(QtGui.QApplication.translate("stegosoft_gui", "Type Here", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_unhide_submit.setText(QtGui.QApplication.translate("stegosoft_gui", "UNHIDE", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_for_unhide_message_files.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("stegosoft_gui", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_for_unhide_message_files.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("stegosoft_gui", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_for_unhide_message_files.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("stegosoft_gui", "Encrypted", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_show_message_files.setText(QtGui.QApplication.translate("stegosoft_gui", "Show Files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_unhide), QtGui.QApplication.translate("stegosoft_gui", "UNHIDE", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_help), QtGui.QApplication.translate("stegosoft_gui", "HELP", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("stegosoft_gui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-style:italic;\">StegoSoft</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version - 1.0</p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">StegoSoft is a software which implements steganography using audio files. This software can hide message files inside a audio file by using the Least Significant Bit Algorithm.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; text-decoration: underline; color:#000000;\">Developed by:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">Rohit Gupta</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">E-mail: rohit.kgec@gmail.com</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">as a Final Year Project,</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">B.Tech - IT</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">Kalyani Government Engineering College,</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">Kalyani, Nadia (W.B.), India</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\"></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:12pt; color:#000000;\">License</span><span style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\">: GNU General Public License version 2.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; color:#000000;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), QtGui.QApplication.translate("stegosoft_gui", "ABOUT", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
